import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

/**
 * Builds a small npm project that makes every classic publishing mistake, in a temp dir.
 * Secret-shaped strings are assembled at runtime so no real-looking tokens live in this repo.
 */
export function createLeakyProject(): string {
  const dir = mkdtempSync(join(tmpdir(), "packpeek-demo-"));
  const put = (rel: string, content: string): void => {
    const p = join(dir, rel);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
  };

  put(
    "package.json",
    JSON.stringify(
      {
        name: "acme-cli",
        version: "2.4.0",
        description: "Demo package generated by packpeek",
        main: "dist/index.js",
        types: "dist/index.d.ts",
        bin: { acme: "dist/cli.js" },
        scripts: { build: "tsup", postinstall: "node dist/setup.js" },
      },
      null,
      2,
    ),
  );

  // Deterministic pseudo-source so the source map has realistic weight.
  const sources: string[] = [];
  const contents: string[] = [];
  for (let i = 0; i < 42; i++) {
    const name = `../src/${["api", "auth", "billing", "cache", "cli", "config", "db", "jobs", "log", "util", "queue"][i % 11]}/module${i}.ts`;
    const body = Array.from({ length: 140 }, (_, n) => `export function handler${i}_${n}(input: string): string { return input.trim() + "${i}-${n}"; }`).join("\n");
    sources.push(name);
    contents.push(body);
  }
  const map = JSON.stringify({ version: 3, file: "cli.js", sources, sourcesContent: contents, names: [], mappings: "AAAA;".repeat(2000) });

  put("dist/index.js", '"use strict";\nmodule.exports = { run: () => "ok" };\n');
  put("dist/cli.js", '#!/usr/bin/env node\nrequire("./index.js").run();\n//# sourceMappingURL=cli.js.map\n');
  put("dist/cli.js.map", map);
  put("dist/vendor.js", `(function(){/* vendor bundle */})();\n//# sourceMappingURL=https://storage.example.com/acme-build/maps/vendor.js.map\n`);
  put("dist/setup.js", 'console.log("setup");\n');
  put(
    "dist/config.js",
    [
      "// generated by build",
      `module.exports = { root: "${"/Users/" + "jane.doe"}/work/acme-cli/src", api: "https://api.acme.example" };`,
      `const GH = "${"ghp_" + "aZ3kQ9mX2vB7nL5cR8tY1wE4uH6jD0pF3gSi".slice(0, 36)}";`,
      "",
    ].join("\n"),
  );
  put(
    ".env",
    ["NODE_ENV=production", `STRIPE_SECRET_KEY=${"sk_live_" + "51Hq8dLkTz3VnWb7YcXe9RfA".slice(0, 24)}`, "SESSION_SECRET=8f3c1a9d0b7e44f2a6d5c91e7b20f4aa", ""].join("\n"),
  );
  put("src/index.ts", "export const run = () => 'ok';\n");
  put("test/cli.test.js", "test('runs', () => {});\n");
  put("test/fixtures/big.json", JSON.stringify({ rows: Array.from({ length: 4000 }, (_, i) => ({ id: i, v: "x".repeat(40) })) }));
  put("coverage/lcov-report/index.html", "<html>" + "<tr><td>covered</td></tr>".repeat(24000) + "</html>");
  put("docs/guide.md", "# Guide\n");
  return dir;
}
